// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2ViydBvdzRAMEwksSspeIyEbqN9gvVY',
    appId: '1:812157837539:android:2db82d33c59e0c4be9e5d6',
    messagingSenderId: '812157837539',
    projectId: 'weekly-features',
    storageBucket: 'weekly-features.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLm9ndjzYLwwJ1Fri8Ph5735i8Ss5kROA',
    appId: '1:812157837539:ios:f5f439dfae7ef737e9e5d6',
    messagingSenderId: '812157837539',
    projectId: 'weekly-features',
    storageBucket: 'weekly-features.appspot.com',
    androidClientId: '812157837539-c31apfl2avlllvdqsdcrj4juml4qkihl.apps.googleusercontent.com',
    iosClientId: '812157837539-6vjn3rbc4n25tkl46vui97b6p1ou4t1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weeklyFeatures',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35Q11UGmR98v8wtvHjy8lbb1U5uKexnk',
    appId: '1:812157837539:web:1517b8cea23d0aa1e9e5d6',
    messagingSenderId: '812157837539',
    projectId: 'weekly-features',
    authDomain: 'weekly-features.firebaseapp.com',
    storageBucket: 'weekly-features.appspot.com',
    measurementId: 'G-DF49725TWL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLm9ndjzYLwwJ1Fri8Ph5735i8Ss5kROA',
    appId: '1:812157837539:ios:f5f439dfae7ef737e9e5d6',
    messagingSenderId: '812157837539',
    projectId: 'weekly-features',
    storageBucket: 'weekly-features.appspot.com',
    androidClientId: '812157837539-c31apfl2avlllvdqsdcrj4juml4qkihl.apps.googleusercontent.com',
    iosClientId: '812157837539-6vjn3rbc4n25tkl46vui97b6p1ou4t1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weeklyFeatures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA35Q11UGmR98v8wtvHjy8lbb1U5uKexnk',
    appId: '1:812157837539:web:a7642bee6f167c5be9e5d6',
    messagingSenderId: '812157837539',
    projectId: 'weekly-features',
    authDomain: 'weekly-features.firebaseapp.com',
    storageBucket: 'weekly-features.appspot.com',
    measurementId: 'G-6LJ9Q6F4F8',
  );

}